# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               adamjames dot github dot io
tagline:             '"Still a better TLD than .blog"'
description:         'Words and other things written by <a href="https://twitter.com/mrwizrd">@mrwizrd</a>. Built with <a href="http://jekyllrb.com/">Jekyll</a> using <a href="https://twitter.com/mdo">@mdo</a>''s excellent <a href="http://lanyon.getpoole.com/">Lanyon</a> theme.'
url:                 http://adamjames.github.io/
postimagesurl:       http://adamjames.github.io/public/postimages/
baseurl:             /
paginate:            4

# About/contact
author:
  name:              Adam Lee james
  url:               https://keybase.io/mrwizrd
  email:             adam@adamjames.me

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/adamjames/adamjames.github.io
