# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               adamjames dot github dot io
tagline:             '"Still a better TLD than .blog"'
description_top:     'Words written by <a href="https://twitter.com/mrwizrd">@mrwizrd</a>. Built with <a href="http://jekyllrb.com/">Jekyll</a> using <a href="https://twitter.com/mdo">@mdo</a>''s excellent <a href="http://lanyon.getpoole.com/">Lanyon</a> theme.'
description_bottom:  'Looking for something else? You should check out my website at <a href="http://www.adamjames.me">adamjames.me</a>!'
use_custom_css:      true
url:                 https://adamjames.github.io/
postimagesurl:       https://adamjames.github.io/public/postimages/
baseurl:             /
paginate:            4
exclude: [README.md, Vagrantfile, .gitignore, .vagrant]

# About/contact
author:
  name:              Adam Lee james
  url:               https://keybase.io/mrwizrd
  email:             adam@adamjames.me

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/adamjames/adamjames.github.io
